FROM ubuntu:20.04

# Set non-interactive mode for apt
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    python3 \
    python3-pip \
    python3-setuptools \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Create a symbolic link for python (since some scripts expect 'python' instead of 'python3')
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws/

# Install QUAST 5.3.0
RUN wget "https://github.com/ablab/quast/releases/download/quast_5.3.0/quast-5.3.0.tar.gz" && \
    tar -xzf quast-5.3.0.tar.gz && \
    rm quast-5.3.0.tar.gz

# Set environment variables for QUAST
ENV PATH="/quast-5.3.0:$PATH"

# Test installations
RUN quast.py --version && aws --version

# Set default working directory
WORKDIR /data

CMD ["/bin/bash"]
