name: assembly-nf-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::nextflow=23.10.1
  - conda-forge::python=3.11.0
  - conda-forge::pip=22.3.1
  - bioconda::seqtk=1.3-0
  - bioconda::bbmap=38.90
  - bioconda::bwa=0.7.17
  - bioconda::samtools=1.7
  - bioconda::picard=2.20.0
  - bioconda::spades=3.15.4
  - bioconda::blast=2.13.0