

library
```{r}
library(dplyr)
library(ggplot2)
```



##
```{r}

list.files("../nf_concordence_out/")

read_file = function (x){
  
  df = readr::read_table(x, col_names = F) 
  names(df) = c("group", "SNP_position_count", "MAF_mean", "genotyping_rate", "r_squared")
  
  df = df %>% 
    dplyr::mutate( sample = x) %>% 
    dplyr::mutate( sample = stringr::str_extract_all( sample, "[GH][0-9]{2}depth[0-9]{1,}x", simplify = T)) %>% 
    dplyr::mutate( sample = as.character(sample)) %>% 
    dplyr::mutate( well = stringr::str_extract_all( sample, "[GH][0-9]{2}", simplify = T)) %>% 
    dplyr::mutate( well = as.character(well)) %>% 
    dplyr::mutate( depth = stringr::str_extract_all( sample, "depth[0-9]{1,}x", simplify = T)) %>% 
    dplyr::mutate( depth = as.character(depth)) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "(x|depth)", "" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "01", "0.1" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "02", "0.2" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "05", "0.5" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "08", "0.8" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "15", "1.5" )) %>% 
    dplyr::mutate( r_squared = round(r_squared, 3)) %>% 
    dplyr::mutate( method = ifelse( grepl("G", well), "Manual", "Sciclone")) %>% 
    dplyr::mutate( depth = paste0( depth, "x")) %>% 
    dplyr::mutate( depth = factor(depth, levels = c("0.1x", "0.2x", "0.5x", "0.8x", "1x", "1.5x"), ordered = T))
  return(df)
  
}

path_all = list.files("../nf_concordence_out/", full.names = T)

df_res = purrr::map_dfr( path_all, read_file)

```



##
```{r}

df_res

table(df_res$depth)



```



## depth 1.5, 5ng, test
```{r}
well_group="[GH]11"
df_rep1 = df_res %>% 
  dplyr::filter( grepl(well_group, well)) %>% 
  dplyr::filter( depth !="2x") %>% 
  dplyr::mutate( real_label = ifelse( grepl("G", well),r_squared, "" ))

df_rep1

my_labels = c("0-0.01","0.01-0.02","0.02-0.05","0.05-0.1", "0.1-0.2","0.2-0.3", "0.3-0.4", "0.4-0.5")
my_labels = c("0.01","0.02","0.05","0.1", "0.2","0.3", "0.4", "0.5")
# df_rep1 %>% 
#   ggplot(aes( group, r_squared, colour = method, label = real_label )) +
#   geom_point() +
#   geom_line() +
#   ylim(0.7,1.05) +
#   facet_wrap(~ depth) + 
#   ggrepel::geom_label_repel()+
#   scale_x_continuous(breaks=seq(0,7,1),labels=my_labels) 

df_rep1 %>% 
  ggplot(aes( group, r_squared, colour = method )) +
  geom_point() +
  geom_line() +
  ylim(0.7,1.05) + 
  facet_wrap(~ depth) + 
  geom_text(aes(y = r_squared, label= real_label), hjust= 0.5, vjust = -2, size= 2.0, color= "black") +
  scale_x_continuous(breaks=seq(0,7,1),labels=my_labels) +
  xlab("MAF")

?ggsave()
ggsave("figures/test.jpg", width =8, height=6)
```
50ng
50ng
40ng
40ng
25ng
25ng
20ng
20ng
10ng
10ng
5ng
5ng

### at different input
```{r}

well_group_list= c("[GH]01", "[GH]02", "[GH]03", "[GH]04", "[GH]05","[GH]06","[GH]07","[GH]08","[GH]09","[GH]10", "[GH]11" , "[GH]12")
input_list = c("50ng", "50ng", "40ng", "40ng", "25ng","25ng","20ng","20ng","10ng","10ng","5ng","5ng")

my_labels = c("0.01","0.02","0.05","0.1", "0.2","0.3", "0.4", "0.5")

get_plot_1 = function(x, y){
  
  df_rep1 = df_res %>% 
  dplyr::filter( grepl(well_group, well)) %>% 
  dplyr::filter( depth !="2x") %>% 
  dplyr::mutate( real_label = ifelse( grepl("G", well),r_squared, "" ))

df_rep1 %>% 
  ggplot(aes( group, r_squared, colour = method )) +
  geom_point() +
  geom_line() +
  ylim(0.7,1.05) + 
  facet_wrap(~ depth) + 
  geom_text(aes(y = r_squared, label= real_label), hjust= 0.5, vjust = -2, size= 2.0, color= "black") +
  scale_x_continuous(breaks=seq(0,7,1),labels=my_labels) +
  xlab("MAF") +
  ggtitle(y)

ggsave(paste0("figures/",x, "_" , y,  "_rsquared_at_different_MAF.jpg"), width =8, height=6)
  
}

purrr::walk2( well_group_list, input_list,get_plot_1  )


```








