
library
```{r}
library(dplyr)
```


##
```{r}

list.files("../GATK_concordance_out/")

read_file = function (x){
  
  df = readr::read_tsv(x) 
  
  
  df = df %>% 
    dplyr::mutate( sample = x) %>% 
    dplyr::mutate( sample = stringr::str_extract_all( sample, "[GH][0-9]{2}depth[0-9]{1,}x", simplify = T)) %>% 
    dplyr::mutate( sample = as.character(sample)) %>% 
    dplyr::mutate( well = stringr::str_extract_all( sample, "[GH][0-9]{2}", simplify = T)) %>% 
    dplyr::mutate( well = as.character(well)) %>% 
    dplyr::mutate( depth = stringr::str_extract_all( sample, "depth[0-9]{1,}x", simplify = T)) %>% 
    dplyr::mutate( depth = as.character(depth)) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "(x|depth)", "" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "01", "0.1" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "02", "0.2" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "05", "0.5" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "08", "0.8" )) %>% 
    dplyr::mutate( depth = stringr::str_replace_all(depth, "15", "1.5" )) %>% 
    dplyr::mutate( method = ifelse( grepl("G", well), "Manual", "Sciclone")) %>% 
    dplyr::filter( type =="SNP") %>% 
    dplyr::mutate( depth = as.numeric(depth)) 
  return(df)
  
}

path_all = list.files("../GATK_concordance_out/", full.names = T)

df_res = purrr::map_dfr( path_all, read_file)



```




##
```{r}

df_res

```



##
```{r}

well_group_list_1= c("G01", "G02", "G03", "G04", "G05","G06","G07","G08","G09","G10", "G11" , "G12")
well_group_list_2= c("H01", "H02", "H03", "H04", "H05","H06","H07","H08","H09","H10", "H11" , "H12")

input_list_1 = c("50ng", "50ng", "40ng", "40ng", "25ng","25ng","20ng","20ng","10ng","10ng","5ng","5ng")
input_list_2 = c("50ng", "50ng", "40ng", "40ng", "25ng","25ng","20ng","20ng","10ng","10ng","5ng","5ng")

well_group = c(well_group_list_1, well_group_list_2)
input_list = c(input_list_1, input_list_1)
info_df = data.frame( well =well_group, input = input_list, stringsAsFactors = F )

my_labels = c("0.1x", "0.2x", "0.5x", "0.8x", "1x", "1.5x")
depth_df = data.frame( depth= c(0.1, 0.2, 0.5, 0.8, 1, 1.5),
                       depth_group = c(1,2,3,4,5,6),
                       stringsAsFactors = F)

df_rep2 = df_res %>% 
  dplyr::left_join(info_df, by ="well") %>% 
  dplyr::left_join( depth_df, by = "depth") %>% 
  dplyr::filter( depth !=2 ) %>% 
  dplyr::mutate( real_label = ifelse( grepl("Manual", method),RECALL, "" )) %>% 
  dplyr::mutate( real_label = RECALL ) %>% 
  dplyr::mutate( REP_group = ifelse( grepl("(01|03|05|07|09|11)", well), "Rep1", "Rep2")) %>% 
  dplyr::mutate( input = factor(input, levels = c("5ng", "10ng", "20ng", "25ng", "40ng","50ng"), ordered = T ))




cols = c("#a7c7ea", "#2e486a")
df_rep2 %>% 
  ggplot(aes( depth_group, RECALL, fill = method )) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid( REP_group ~ input) +
#  geom_text(aes(y = RECALL, label= real_label), hjust= 0.5, vjust = -2, size= 1.5, color= "black") +
  xlab("x_depth") +
  scale_x_continuous(breaks=seq(1,6,1),labels=my_labels)  +
  scale_fill_manual(values=cols)


ggsave("figures/RECALL_bar.jpg", width =25, height=12)









```
