
##plot by coverage by GC

library
```{r}

library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(zoo)


```


## get the contig of the largest: test
```{r}

list.files("res/cov")

file = "res/cov/Bacillus_cereus_A2001_F06.bedcov.txt"

df = readr::read_table( file, col_names = F)


names(df) = c("contig", "start", "end", "cov")

df_s = df %>% 
  tidyr::nest( - contig) %>% 
  dplyr::mutate( data2 = purrr::map(.$data, function(x){
    n = nrow(x)
    x = x %>% 
      dplyr::mutate( kb_length = n)
    return(x)
  })) %>% 
  dplyr::select( contig, data2) %>% 
  tidyr::unnest()

table(df_s$kb_lengh, useNA = "ifany")

n_max = max(df_s$kb_length, na.rm = T)

df_ss = df_s %>% 
  dplyr::filter( kb_length == n_max )

```


## get the contig of the largest: function
```{r}

get_cov_data = function(file_path){
  
  
  df = readr::read_table( file_path, col_names = F)
  
  sample_ID = stringr::str_replace( basename(file_path), ".bedcov.txt", "" )
  
  names(df) = c("contig", "start", "end", "cov")
  
  df_s = df %>% 
    tidyr::nest( - contig) %>% 
    dplyr::mutate( data2 = purrr::map(.$data, function(x){
      n = nrow(x)
      x = x %>% 
        dplyr::mutate( kb_length = n)
      return(x)
    })) %>% 
    dplyr::select( contig, data2) %>% 
    tidyr::unnest()
  
  table(df_s$kb_lengh, useNA = "ifany")
  
  n_max = max(df_s$kb_length, na.rm = T)
  
  df_ss = df_s %>% 
    dplyr::filter( kb_length == n_max ) %>% 
    dplyr::mutate( sample_ID = sample_ID)  %>% 
    dplyr::select( -kb_length)
  
  return(df_ss)
  
  
}

file_path = list.files( "res/cov", full.names = T)

df_cov = purrr::map_dfr( file_path, get_cov_data )

table(df_cov$contig)

df_cov
```


## get the GC from reference
```{r}

read_GC = function(path){
  
  df = readr::read_table( path)
  
  names(df)[c(1,2,3, 5)] = c("contig", "start", "end", "GC_content")
  df_s = df %>% 
    dplyr::select( contig, start, end, GC_content ) %>% 
    tidyr::nest( - contig) %>% 
    dplyr::mutate( data2 = purrr::map(.$data, function(x){
      n = nrow(x)
      x = x %>% 
        dplyr::mutate( kb_length = n)
      return(x)
    })) %>% 
    dplyr::select( contig, data2) %>% 
    tidyr::unnest()
  
  table(df_s$kb_lengh, useNA = "ifany")
  
  n_max = max(df_s$kb_length, na.rm = T)
  
  df_ss = df_s %>% 
    dplyr::filter( kb_length == n_max ) %>% 
    dplyr::select( -kb_length)
  
  return(df_ss)
  
}

gc_file_list = list.files("res/GC/", full.names = TRUE)


gc_df = purrr::map_dfr( gc_file_list, read_GC)

table(gc_df$contig)
table(df_cov$contig)


```


##
```{r}

df_gc_cov = gc_df %>% 
  dplyr::left_join( df_cov, by = c("contig", "start", "end")) 

 df_gc_cov$rolling_cov <- rollmean(df_gc_cov$cov, 5, fill = NA, align = "right")

df_gc_cov
```


## plot test
```{r}

sample_id= "Bacillus_cereus_A2001_F06"

df_plot_s = df_gc_cov %>% 
  dplyr::filter( sample_ID == sample_id) 

avg_cov = mean(df_plot_s$rolling_cov, na.rm = T)
df_plot_ss = df_plot_s %>% 
  dplyr::mutate( coverage = rolling_cov/avg_cov)


reds=colorRampPalette(c("red", "white"))
blues=colorRampPalette(c("white", "blue"))




df_plot_ss %>% 
  dplyr::mutate( row = 1:nrow(.)) %>% 
  ggplot(aes(row, coverage, color = GC_content)) +
  geom_bar(stat = "identity") +
  scale_color_gradientn(colors=c(reds(30), blues(60))) +
  xlab("kb")


df_plot_ss %>% 
  dplyr::mutate( row = 1:nrow(.)) %>% 
  ggplot(aes(row, coverage)) +
  geom_area( fill = "blue")+
  xlab("kb")
  


```



## function to get the plot
```{r}

sample_id_list = unique(df_gc_cov$sample_ID)



reds=colorRampPalette(c("red", "white"))
blues=colorRampPalette(c("white", "blue"))

get_plot = function(x ){
  
  sample_id= x
  
  df_plot_s = df_gc_cov %>% 
    dplyr::filter( sample_ID == sample_id) 
  
  avg_cov = mean(df_plot_s$rolling_cov, na.rm = T)
df_plot_ss = df_plot_s %>% 
  dplyr::mutate( coverage = rolling_cov/avg_cov)

  
  df_plot_ss %>% 
  dplyr::mutate( row = 1:nrow(.)) %>% 
  ggplot(aes(row, coverage, color = GC_content)) +
  geom_bar(stat = "identity") +
  scale_color_gradientn(colors=c(reds(30), blues(60))) +
  xlab("kb")  +
  ggtitle(sample_id)
  
  ggsave( paste0( "plots/", x, "_gc_cov.jpg") )
  
  
}

purrr::walk( sample_id_list, get_plot )


```


## geom_area plot
```{r}


get_plot_area = function(x ){
  
  sample_id= x
  
  df_plot_s = df_gc_cov %>% 
    dplyr::filter( sample_ID == sample_id) 
  
  avg_cov = mean(df_plot_s$rolling_cov, na.rm = T)
  df_plot_ss = df_plot_s %>% 
    dplyr::mutate( coverage = rolling_cov/avg_cov)
  
  
  df_plot_ss %>% 
    dplyr::mutate( row = 1:nrow(.)) %>% 
    ggplot(aes(row, coverage)) +
    geom_area( fill = "blue")+
    xlab("kb") +
    ggtitle(sample_id)
  
  ggsave( paste0( "cov_area_plots/", x, "_gc_cov.jpg") )
  
  
}

purrr::walk( sample_id_list, get_plot_area )

```
